package com.redhat.bpms.example.pmi;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("mortgage application")
public class MortgageApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("base loan amount")
	@org.kie.api.definition.type.Label("length of loan (years)")
	private java.lang.String lengthOfLoanYears;
	private java.lang.Integer baseLoanAmount;
	@org.kie.api.definition.type.Label("down payment")
	private java.lang.Integer downpayment;
	@org.kie.api.definition.type.Label("rate")
	private java.lang.Float rate;
	@org.kie.api.definition.type.Label("annual MIP (bps)")
	private java.lang.Integer annualMIP;


	public MortgageApplication() {
	}

	public java.lang.Integer getBaseLoanAmount() {
		return this.baseLoanAmount;
	}

	public void setBaseLoanAmount(java.lang.Integer baseLoanAmount) {
		this.baseLoanAmount = baseLoanAmount;
	}

	public java.lang.Integer getAnnualMIP() {
		return this.annualMIP;
	}

	public void setAnnualMIP(java.lang.Integer annualMIP) {
		this.annualMIP = annualMIP;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getLengthOfLoanYears() {
		return this.lengthOfLoanYears;
	}

	public void setLengthOfLoanYears(java.lang.String lengthOfLoanYears) {
		this.lengthOfLoanYears = lengthOfLoanYears;
	}

	public java.lang.Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public java.lang.Float getRate() {
		return this.rate;
	}

	public void setRate(java.lang.Float rate) {
		this.rate = rate;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public MortgageApplication(java.lang.Integer baseLoanAmount,
			java.lang.Integer annualMIP, java.lang.String type,
			java.lang.String lengthOfLoanYears, java.lang.Integer downpayment,
			java.lang.Float rate, java.lang.String id) {
		this.baseLoanAmount = baseLoanAmount;
		this.annualMIP = annualMIP;
		this.type = type;
		this.lengthOfLoanYears = lengthOfLoanYears;
		this.downpayment = downpayment;
		this.rate = rate;
		this.id = id;
	}

}