package com.redhat.bpms.example.pmi;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("mortgage application")
public class MortgageApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "base loan amount")
	private java.lang.Integer baseLoanAmount;
	@org.kie.api.definition.type.Label(value = "annual MIP (bps)")
	private java.lang.Integer annualMIP;
	@org.kie.api.definition.type.Label(value = "type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "length of loan (years)")
	private java.lang.String lengthOfLoanYears;
	@org.kie.api.definition.type.Label(value = "down payment")
	private java.lang.Integer downpayment;
	@org.kie.api.definition.type.Label(value = "rate")
	private java.lang.Float rate;

	public MortgageApplication() {
	}

	public java.lang.Integer getBaseLoanAmount() {
		return this.baseLoanAmount;
	}

	public void setBaseLoanAmount(java.lang.Integer baseLoanAmount) {
		this.baseLoanAmount = baseLoanAmount;
	}

	public java.lang.Integer getAnnualMIP() {
		return this.annualMIP;
	}

	public void setAnnualMIP(java.lang.Integer annualMIP) {
		this.annualMIP = annualMIP;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getLengthOfLoanYears() {
		return this.lengthOfLoanYears;
	}

	public void setLengthOfLoanYears(java.lang.String lengthOfLoanYears) {
		this.lengthOfLoanYears = lengthOfLoanYears;
	}

	public java.lang.Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public java.lang.Float getRate() {
		return this.rate;
	}

	public void setRate(java.lang.Float rate) {
		this.rate = rate;
	}

	public MortgageApplication(java.lang.Integer baseLoanAmount,
			java.lang.Integer annualMIP, java.lang.String type,
			java.lang.String lengthOfLoanYears, java.lang.Integer downpayment,
			java.lang.Float rate) {
		this.baseLoanAmount = baseLoanAmount;
		this.annualMIP = annualMIP;
		this.type = type;
		this.lengthOfLoanYears = lengthOfLoanYears;
		this.downpayment = downpayment;
		this.rate = rate;
	}

}