package com.redhat.bpms.example.pmi;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("property")
public class Property implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "price")
	private java.lang.Integer price;
	@org.kie.api.definition.type.Label(value = "address")
	private java.lang.String address;

	public Property() {
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public Property(java.lang.Integer price, java.lang.String address) {
		this.price = price;
		this.address = address;
	}

}